### ISSUE TITLE
전반적인 코드 리팩토링을 진행한다

### ISSUE THREAD

**Issue by chaeeerish** [chaeeerish/StockOneQ-back#4]
## Description 🖊️
- 전반적인 코드 리팩토링을 진행한다

## To-do 🧑‍💻
- [ ] 코드 스타일 통일
- [ ] 불필요한 클래스와 메서드를 삭제한다
- [ ] Spring Security 추가에 따른 @ExtractToken -> @Auth 어노테이션 변경
