### ISSUE TITLE
Spring Security Controller Unit Test 작성한다

### ISSUE THREAD

**Issue by chaeeerish** [chaeeerish/StockOneQ-back#7]
## Description 🖊️
Spring Security Controller Unit Test 작성하기

## To-do 🧑‍💻
- [ ] Spring Security 테스트 코드 추가
- [ ] Custom한 @WithMockUser 생성하기
- [ ] WithSecurityContextFactory 구현하기
- [ ] Spring Rest Docs의 snippets 수정하기
- [ ] 모든 Test 통과하도록 수정하기
- [ ] Test 코드 리팩토링하기

## ETC ➕
- https://dwaejinho.tistory.com/entry/%EC%BB%A4%EC%8A%A4%ED%85%80-UserDetails-SecurityContext-Test-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0
- https://velog.io/@da_na/Spring-Security-JWT-Spring-Security-Controller-Unit-Test%ED%95%98%EA%B8%B0
- https://velog.io/@onetuks/WithMockUser-WithUserDetails-WithSecurityContext
